export const data = [
    {
        id: 1,
        title: "Buy of $34,00",
        danger: 2,
        status: "open",
        trader: "Hugo justice",
        couterParty: "Guerra corporation",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 2,
        title: "Sell of $32.3M",
        danger: 1,
        status: "escalated",
        trader: "Hugo justice",
        couterParty: "VALE corp 2",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 3,
        title: "Sell of $35.0M",
        danger: 1,
        status: "closed",
        trader: "Hugo justice",
        couterParty: "VALE corp 3",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 4,
        title: "Sell of $340.0M",
        danger: 0,
        status: "open",
        trader: "Hugo justice",
        couterParty: "VALE corp 4",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 5,
        title: "Sell of $13.0M",
        danger: 0,
        status: "closed",
        trader: "Hugo justice",
        couterParty: "VALE corp 5",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 6,
        title: "Sell of $38.0M",
        danger: 1,
        status: "closed",
        trader: "Hugo justice",
        couterParty: "VALE corp 6",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 7,
        title: "Sell of $323.0M",
        danger: 0,
        status: "closed",
        trader: "Hugo justice",
        couterParty: "VALE corp 7",
        book: "phhi-z53",
        source: "Bank Thrading",
    },
    {
        id: 8,
        title: "Sell of $240.0M",
        danger: 2,
        status: "closed",
        trader: "Hugo justice",
        couterParty: "VALE corp 8",
        book: "phhi-z53",
        source: "Bank Thrading",
    }
]